spring.application.name=campusiq-backend

# ================= DATABASE =================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campusiq_platform_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ================= SERVER =================

server.port=${PORT:8080}
server.address=0.0.0.0

# ================= JWT =================

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ================= GMAIL =================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:campusiq.pesmcoe2027@gmail.com}
spring.mail.password=${MAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ================= ESP32 =================

campusiq.esp32.device-id=${ESP32_DEVICE_ID:ESP32-LAB-01}
campusiq.esp32.device-secret=${ESP32_DEVICE_SECRET}
campusiq.esp32.serial-port=${ESP32_SERIAL_PORT:COM18}
campusiq.esp32.serial-baud-rate=${ESP32_SERIAL_BAUD_RATE:115200}

# ================= CAMPUS-IQ ADMIN =================

campusiq.admin.username=${CAMPUSIQ_ADMIN_USERNAME:campusiq.admin}
campusiq.admin.password=${CAMPUSIQ_ADMIN_PASSWORD:}

# ================= CAMPUS-IQ AI =================

campusiq.ai.provider=${AI_PROVIDER:groq}

# ================= OPENAI =================

campusiq.ai.openai.api-key=${OPENAI_API_KEY:}
campusiq.ai.openai.model=${OPENAI_MODEL:gpt-5.6-luna}
campusiq.ai.openai.base-url=${OPENAI_BASE_URL:https://api.openai.com/v1}

# ================= GROQ =================

campusiq.ai.groq.api-key=${GROQ_API_KEY:}
campusiq.ai.groq.model=${GROQ_MODEL:openai/gpt-oss-20b}
campusiq.ai.groq.base-url=${GROQ_BASE_URL:https://api.groq.com/openai/v1}






# spring.application.name=campusiq-backend

# # ================= DATABASE =================

# spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campusiq_platform_db}
# spring.datasource.username=${DB_USERNAME:root}
# spring.datasource.password=${DB_PASSWORD}

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=false
# spring.jpa.open-in-view=false

# # ================= SERVER =================

# server.port=${PORT:8080}
# server.address=0.0.0.0

# # ================= JWT =================

# app.jwt.secret=${JWT_SECRET}
# app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# # ================= GMAIL =================

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587

# spring.mail.username=${MAIL_USERNAME:campusiq.pesmcoe2027@gmail.com}
# spring.mail.password=${MAIL_APP_PASSWORD}

# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true

# # ================= ESP32 =================

# campusiq.esp32.device-id=${ESP32_DEVICE_ID:ESP32-LAB-01}
# campusiq.esp32.device-secret=${ESP32_DEVICE_SECRET}
# campusiq.esp32.serial-port=${ESP32_SERIAL_PORT:COM18}
# campusiq.esp32.serial-baud-rate=${ESP32_SERIAL_BAUD_RATE:115200}

# # ================= CAMPUS-IQ ADMIN =================

# campusiq.admin.username=${CAMPUSIQ_ADMIN_USERNAME:campusiq.admin}
# campusiq.admin.password=${CAMPUSIQ_ADMIN_PASSWORD:}

# # ================= CAMPUS-IQ AI =================

# campusiq.ai.provider=${AI_PROVIDER:groq}

# # ================= OPENAI =================

# campusiq.ai.openai.api-key=${OPENAI_API_KEY:}
# campusiq.ai.openai.model=${OPENAI_MODEL:gpt-5.6-luna}
# campusiq.ai.openai.base-url=${OPENAI_BASE_URL:https://api.openai.com/v1}

# # ================= GROQ =================

# campusiq.ai.groq.api-key=${GROQ_API_KEY:}
# campusiq.ai.groq.model=${GROQ_MODEL:openai/gpt-oss-20b}
# campusiq.ai.groq.base-url=${GROQ_BASE_URL:https://api.groq.com/openai/v1}








# #spring.application.name=campusiq-backend
# #
# ## ================= DATABASE =================
# #
# #spring.datasource.url=jdbc:mysql://localhost:3306/campusiq_platform_db
# #spring.datasource.username=root
# #spring.datasource.password=${DB_PASSWORD}
# #
# #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# #
# #spring.jpa.hibernate.ddl-auto=update
# #spring.jpa.show-sql=true
# #spring.jpa.properties.hibernate.format_sql=true
# #spring.jpa.open-in-view=false
# #
# #server.port=8080
# #server.address=0.0.0.0
# #
# #
# ## ================= JWT =================
# #
# #app.jwt.secret=${JWT_SECRET:Q2FtcHVzSVEtRGV2ZWxvcG1lbnQtSldULVNlY3JldC0yMDI2IQ==}
# #app.jwt.expiration-ms=86400000
# #
# #
# ## ================= GMAIL =================
# #
# #spring.mail.host=smtp.gmail.com
# #spring.mail.port=587
# #
# #spring.mail.username=campusiq.pesmcoe2027@gmail.com
# #spring.mail.password=${MAIL_APP_PASSWORD}
# #
# #spring.mail.properties.mail.smtp.auth=true
# #spring.mail.properties.mail.smtp.starttls.enable=true
# #spring.mail.properties.mail.smtp.starttls.required=true
# #
# #
# ## ================= ESP32 =================
# #
# #campusiq.esp32.device-id=${ESP32_DEVICE_ID:ESP32-LAB-01}
# #campusiq.esp32.device-secret=${ESP32_DEVICE_SECRET:CampusIQ-ESP32-Secret-2026}
# #
# ## ================= CAMPUS-IQ ADMIN =================
# #
# #campusiq.admin.username=${CAMPUSIQ_ADMIN_USERNAME:campusiq.admin}
# #campusiq.admin.password=${CAMPUSIQ_ADMIN_PASSWORD:}
# #
# ## ================= CAMPUS-IQ AI =================
# #
# #campusiq.ai.provider=groq
# #
# #
# #
# ## ================= OPENAI =================
# #
# #campusiq.ai.openai.api-key=${OPENAI_API_KEY:}
# #campusiq.ai.openai.model=${OPENAI_MODEL:gpt-5.6-luna}
# #campusiq.ai.openai.base-url=https://api.openai.com/v1
# #
# #
# ## ================= GROQ =================
# #
# #campusiq.ai.groq.api-key=${GROQ_API_KEY:}
# #campusiq.ai.groq.model=${GROQ_MODEL:openai/gpt-oss-20b}
# #campusiq.ai.groq.base-url=https://api.groq.com/openai/v1
